aws:
  s3:
    bucket-name: test-bucket-nur
    region: ap-south-1
  sqs:
    queue-name: My-test-queue
  sns:
    topic-arn: arn:aws:sns:ap-south-1:115197150226:My-notification-topic

#    access-key:
#    secret-key:
#  sqs:
#    queue-url: https://sqs.ap-south-1.amazonaws.com/115197150226/My-test-queue
