aws:
  s3:
    bucket-name: test-bucket-nur
    region: ap-south-1
  sqs:
    queue-name: My-test-queue

#    access-key:
#    secret-key:
#  sqs:
#    queue-url: https://sqs.ap-south-1.amazonaws.com/115197150226/My-test-queue
